### ISSUE TITLE
Dark Mode: unread notification background

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/humhub-modules-clean-theme#17]
There is an issue reported on https://github.com/felixhahnweilheim/humhub-dark-mode/issues/54

It is only with the clean theme, so I add it here.

It seems this line does not work as expected: https://github.com/cuzy-app/humhub-modules-clean-theme/blob/master/themes/clean-base/less/dark/clean-dark-colors.less#L22

I am not at home today, so I can't look into it but I wanted to let you know @marc-farre

**Comment by marc-farre** [comment]
I don't know.
On my instance, it's even worse:
![image](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/23310825/d5f5fa60-0cdc-4a45-92c0-f83b6613555e)

I don't really have time to maintain the Dark Mode on top of the Clean Theme and I don't use it, so if someone want to fix it, I leave the issue open.

**Comment by marc-farre** [comment]
Thanks very much @felixhahnweilheim !
CSS recompiled and fix published in version 1.7.4: https://github.com/cuzy-app/clean-theme/releases/tag/1.7.4
