### ISSUE TITLE
Position of notifications (+ mail) dropdown on mobile

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/humhub-modules-clean-theme#2]
The notifications dropdown overlaps the screen in the mobile view, see screenshot:

![Screenshot_20220924-121639_Chrome.jpg](https://user-images.githubusercontent.com/84990763/192095479-1903e7c6-74fc-4d32-bfe0-bcf050f8938f.jpg)

The same is with the message dropdown of the mail module:

![Screenshot_20220924-121634_Chrome.jpg](https://user-images.githubusercontent.com/84990763/192095594-c6839cd1-deee-4a67-b84f-b28479a182a1.jpg)

Apart from that great module! Thanks for making it free.

**Comment by funkycram** [comment]
Thanks for reporting this problem!
Fixed with this commit: https://github.com/cuzy-app/humhub-modules-clean-theme/commit/adada2d567ef1dc790a61df781fe2967aebfb618
In release 1.1: https://github.com/cuzy-app/humhub-modules-clean-theme/releases/tag/1.1
