### ISSUE TITLE
Space title hard to read when banner image in use

### ISSUE THREAD

**Issue by dantefromhell** [cuzy-app/humhub-modules-clean-theme#3]
When using a background image in the Space header, the Space title becomes unreadable quickly as the font color is set to `#76838f` - a light grey which has little contrast to mixed-color images.

I can think of a few options
1. Auto-detected background color to adjust font color to a high contrast
2. Create an additional layer in-between the image and the text to blur the image colors
3. Find a high-contrast font color - which might be impossible
4. Add a `text-shadow` that has a high contrast to the font color

None of the solutions feel clean and/ or easy enough to propose as solution, hence the full listing of ideas.

**Comment by funkycram** [comment]
@dantefromhell yes, you're right, this was not good.
Can you test with this new version (unreleased) by cloning the repository https://github.com/cuzy-app/humhub-modules-clean-theme ?

**Comment by dantefromhell** [comment]
Yes, the bar improves readability quite some, great idea.

I've tested a few different values for `background: fade(black, 67%);` on multiple background pictures. On my screen values between 20% to 35% delivered great results and interfered less with the background images a bit less.

If this is of interest to you, I'm happy to send you a PR for 35% - assuming this is the "safer" value.

**Comment by funkycram** [comment]
Thanks for your tests. I agree it's better with 35%.
I've pushed this change and also added `font-weight: 400;` to the space description which was difficult to read with a 35% background.

**Comment by dantefromhell** [comment]
Thanks @funkycram 
Would you mind poking this issue once the changes are released?

**Comment by funkycram** [comment]
Done. It should be available on the marketplace soon: https://marketplace.humhub.com/module/clean-theme/description
