### ISSUE TITLE
CSS border attribute inconsistent for user thumbnails

### ISSUE THREAD

**Issue by dantefromhell** [cuzy-app/humhub-modules-clean-theme#4]
The visual for user thumbnail is formatted inconsistently.

In the `Space members` view, a user thumbnail defines `border: 1px solid #21A1B3;`, which results in the following visual
![image](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/90508808/0c922984-a561-4b25-9e86-308a5648c0ec)

In other places the `border` attribute is not defined, resulting in
![image](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/90508808/6b85cd44-74f3-43bd-b2ab-e6b9ef5978f2)

The places I could identify so far
- `Space member` widget displays border
- `Latest activities` widget does not displays border
- Profile menu (top right) does not display border
- Stream does not display borders
- `People` directory does not display borders

Personally speaking the border provides a little bit of visual boundary and makes for smoother visuals. The metaphor of a picture frame comes to mind. I would prefer a darker color over the
greenish one used in the `Space member` widget.

Not sure though if this matches with the intention of `clean` for this theme. Please disregard my personal preferences if not.

**Comment by dantefromhell** [comment]
Not sure I'm interpreting the logic correctly, but I just recognized in a different space that some profile pictures in the `Space member` widget have the border, others not.

It seems that elevating a users status from `Member` to `Moderator` adds it. The users whose profile pictures are circled are either in the `Moderators` or `Administrator` role of the space.

**Comment by funkycram** [comment]
You're right, it's for Moderators or Administrators.
This border is added by Humhub's core less code and hasn't been overwritten by the Clean Theme.
If you have a better idea to identify Moderators or Administrators with CSS, feel free creating a PR.
Thanks!

**Comment by dantefromhell** [comment]
I like the visual idea for the new online status
https://github.com/humhub/humhub/issues/6295

I could imagine a round circle on the bottom left of the profile image, possible including a letter, like
- **M** for Moderator
- **A** for Administrator
- **O** for Owner

Possibly a little hover text, that eplains the role appreviated by the letter.

**Comment by funkycram** [comment]
I like your idea, and I think it should be done on Humhub core rather than this theme.
Could you suggest it on https://github.com/humhub/humhub/issues?
